---
appName: &name jenkins

route: true

# ovs this is not a real password in use.... or is it?
# ¯\_(ツ)_/¯
source_secret:
  name: git-auth
  username: idm-sa
  password: thisisdefinitelymypassword

deployment:
  openshiftauth: true
  imagestream:
    name: *name
    tag: latest
  limits:
    memory_request: 2Gi
    memory_limit: 6Gi
    cpu_request: 500m
    cpu_limit: 1
  env_vars:
    - name: JVM_ARCH
      value: 'x86_64'
    - name: DISABLE_ADMINISTRATIVE_MONITORS
      value: 'false'
    - name: ENABLE_FATAL_ERROR_LOG_FILE
      value: 'false'
    - name: JENKINS_OPTS
      value: '--sessionTimeout=0'
    - name: SLACK_BASE_URL
      value: ''
    - name: SLACK_ROOM
      value: ''
    - name: SLACK_TOKEN_CREDENTIAL_ID
      value: ''
    - name: SLACK_TEAM
      value: ''
    - name: SHARED_LIB_REPO
      value: ''
    - name: SHARED_LIB_NAME
      value: ''
    - name: SHARED_LIB_REF
      value: ''
    - name: SHARED_LIB_SECRET
      value: ''
    - name: GITLAB_HOST
      value: ''
    - name: GITLAB_TOKEN
      value: ''
    - name: GITLAB_GROUP_NAME
      value: rht-labs

persistence:
  accessModes: ReadWriteOnce
  volumeSize: 20Gi

services:
  - name: *name
    port_name: web
    port: 80
    target_port: 8080
    selector: *name
    annotations: service.alpha.openshift.io/dependencies
  - name: jenkins-jnlp
    port_name: agent
    port: 50000
    target_port: 5000
    selector: *name

imagestream:
  name: *name
  external:
    builder_registry: quay.io
    builder_repo: openshift
    builder_image: origin-jenkins
    builder_imagetag: latest
  builder_repo: openshift
  builder_image: jenkins
  builder_imagetag: '2'

buildconfig:
  name: *name
  build_secret: 'shhhhh-this-is-my-super-duper-secret123-shhhhh'
  source_secret: 'git-auth'
  pull_secret: ''
  source_repo_url: https://github.com/rht-labs/s2i-config-jenkins.git
  source_repo_ref: v1.6
  source_repo_context: ''
