{{- if .Values.imagestream.external.enabled }}
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ .Values.imagestream.name }}
  annotations:
    description: Tracks the Red Hat Jenkins base image, since openshift may not ship with the tag we need. Importing the image allows normal users to run the playbook.
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: {{ .Values.imagestream.external.builder_registry }}/{{ .Values.imagestream.external.builder_repo }}/{{ .Values.imagestream.external.builder_image }}:{{ .Values.imagestream.external.builder_imagetag }}
    importPolicy: {}
    name: {{ .Values.imagestream.builder_imagetag }}
    referencePolicy:
      type: Source
{{- end}}