{{- if .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 4m
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
  name: {{ .Values.appName }}
spec:
  host: {{ .Values.appHostName }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.appName }}
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
{{ end }}