apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Chart.Name }}
    deploymentconfig: postgresql-{{ .Chart.Name }}
  name: postgresql-{{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    app: {{ .Chart.Name }}
    deploymentconfig: postgresql-{{ .Chart.Name }}
  strategy:
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        deploymentconfig: postgresql-{{ .Chart.Name }}
    spec:
      containers:
        - name: postgresql
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.postgresql.secrets.keys.username | default "username" }}
                  name: {{ .Values.secret.name | default "{{ .Chart.Name }}-secrets" }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.postgresql.secrets.keys.password | default "password" }}
                  name: {{ .Values.secret.name | default "{{ .Chart.Name }}-secrets" }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgresql.database | default "pack-broker" }}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.postgresql.service.port | default "5432" }}
            timeoutSeconds: 1
          ports:
            - containerPort: {{ .Values.postgresql.service.port  | default "5432" }}
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -i
                - -c
                - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgresql-{{ .Chart.Name }}-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgresql-{{ .Chart.Name }}-data
          persistentVolumeClaim:
            claimName: postgresql-{{ .Chart.Name }}-data
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:{{ .Values.postgresql.image.tag | default "9.5" }}
          namespace: openshift
      type: ImageChange