apiVersion: v1
kind: Service
metadata:
  name: postgresql-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port | default "5432" }}
      protocol: TCP
      targetPort: {{ .Values.postgresql.service.port | default "5432" }}
  selector:
    app: {{ .Chart.Name }}
    deploymentconfig: postgresql-{{ .Chart.Name }}
  sessionAffinity: None
  type: {{ .Values.postgresql.service.type | default "ClusterIP" }}