{{- if .Values.postgresql }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Chart.Name }}
    deploymentconfig: postgresql-{{ .Chart.Name }}
  name: postgresql-{{ .Chart.Name }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistent.volume.size | default " 5Gi" }}
{{ end }}