{{- if .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  host: null
  port:
    targetPort: {{ .Values.route.targetPort | default "8080" }}-tcp
  to:
    kind: Service
    name: {{ .Values.appName }}
    weight: 100
status:
  ingress:
    - conditions:
      - lastTransitionTime: ""
        status: ""
        type: "" 
      host: ""
      routerCanonicalHostname: ""
      routerName: default
      wildcardPolicy: None
{{ end }}