{{- if .Values.route }}
---
apiVersion: v1
kind: Route
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  port:
    targetPort: {{ .Values.route.targetPort | default "8080" }}-tcp
  to:
    kind: Service
    name: {{ .Chart.Name }}
    weight: 100
  wildcardPolicy: None
{{ end }}