apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secrets
  labels:
    app: {{ .Chart.Name }}
    credential.sync.jenkins.openshift.io: "true"
stringData:
  password: ${POSTGRESQL_PASSWORD}
  username: ${POSTGRESQL_USERNAME}
  pact_broker_admin: ${PACT_BROKER_BASIC_AUTH_USERNAME}
  pact_broker_admin_password: ${PACT_BROKER_BASIC_AUTH_PASSWORD}
  pact_broker_user: ${PACT_BROKER_BASIC_AUTH_READ_ONLY_USERNAME}
  pact_broker_user_password: ${PACT_BROKER_BASIC_AUTH_READ_ONLY_PASSWORD}