apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secrets
  labels:
    app: {{ .Chart.Name }}
    credential.sync.jenkins.openshift.io: "true"
stringData:
  password: {{ .Values.postgresql.secrets.values.password }}
  username: {{ .Values.postgresql.secrets.values.username }}
  pact_broker_admin: {{ .Values.secret.values.pactBrokerBasicAuthUsername}}
  pact_broker_admin_password: {{ .Values.secret.values.pactBrokerBasicAuthPassword }}
  pact_broker_user: {{ .Values.secret.values.pactBrokerBasicAuthReadOnlyUsername }}
  pact_broker_user_password: {{ .Values.secret.values.pactBrokerBasicAuthReadOnlyPassword }}
