{{- if .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: "{{ .Chart.Name }} - {{ .Chart.Version }}"
spec:
  ports:
    - name: {{ .Values.service.port | default "8080" }}-tcp
      port: {{ .Values.service.port | default "8080" }}
      protocol: TCP
      targetPort: {{ .Values.service.port | default "8080" }}
  selector:
    app: {{ .Chart.Name }}
  sessionAffinity: None
  type: {{ .Values.service.type | default "ClusterIP" }}
{{ end }}