# Default values for operatorhub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operators:
  - name: subscription-name
    namespace: operator-namespace
    subscription:
      channel: operator-channel
      approval: approval-type
      operatorName: operator-name
      sourceName: catalog-source
      sourceNamespace: catalog-source-namespace
      csv: optional-catalog-source-version
    operatorgroup:
      create: true
