service:
  type: ClusterIP
  port: 8080

image: 
  repository: "pactfoundation/pact-broker"
  tag: "latest"

route:
  targetPort: 8080

secrets:
  name: "pack-broker"
  keys:
    pactBrokerBasicAuthUsername: pact_broker_admin
    pactBrokerDatabaseHost: postgresql-pact-broker
    username: username
    password: password
  values:
    pactBrokerBasicAuthUsername: postgresql-pack-broker
    pactBrokerBasicAuthPassword: pack_broker_admin_password
    pactBrokerBasicAuthReadOnlyUsername: pact_broker_user
    pactBrokerBasicAuthReadOnlyPassword: pact_broker_user_password

deployment:
  replicaCount: 1
  intervalSeconds: 1
  maxSurge: 25
  maxUnavailable: "25%"
  timeoutSeconds: 600
  updatePeriodSeconds: 1
  livenessProbe:
    path: /diagnostic/status/heartbeat
    failureThreshold: 3
    scheme: HTTP
  pactBrokerPublicHeartbeat: true

persistence:
  enabled: true

postgresql:
  service:
    port: 5432 # default
    database: "pack-broker"
    type: ClusterIP
  image:
    tag: "9.5"
  persistent:
    volume: 
      size: "5gi"
  secrets:
    keys:
      username: username
      password: password
    values:
      username: CHANGE-ME
      password: CHANGE-ME